### Get all santas
GET http://localhost:3000/santa-claus-hoho
Accept: application/json

### Get santa by ID
GET http://localhost:3000/santa-claus-hoho/908f77b0-c445-484c-9d2f-6509a3e0c90
Accept: application/json

### Delete santa by ID
DELETE http://localhost:3000/orangutanes/696697b64bdbce4d7b9dc29e
Accept: application/json

### Create a new santa
POST http://localhost:3000/orangutanes
Content-Type: application/json

{
  "peso": 120,
  "regalos": "Suspensos para todos",
  "color": "Brown",
  "nacionalidad": "Marroquí"
}

### Update a santa by ID
PUT http://localhost:3000/santas/1d681246-608f-457f-99dd-7155e36ba760
Content-Type: application/json

{
  "titulo": "Honda",
  "autor": "CB500F",
  "anio": 6500,
  "id":"1d681246-608f-457f-99dd-7155e36ba760"
}
